# Generated by Django 3.2.17 on 2023-02-14 09:19

from django.db import migrations, models
import ping.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ip', models.CharField(max_length=30, validators=[ping.models.validate_ip])),
            ],
        ),
    ]
