# Generated by Django 3.2.17 on 2023-02-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='uefi',
            field=models.BooleanField(default=False),
        ),
    ]
