# Generated by Django 3.2.17 on 2023-02-14 12:52

from django.db import migrations, models
import ping.models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0003_alter_setup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[ping.models.validate_name]),
        ),
    ]
