# Generated by Django 3.2.17 on 2023-02-14 12:52

from django.db import migrations, models
import ping.models


class Migration(migrations.Migration):

    dependencies = [
        ('ping', '0004_alter_setup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='ip',
            field=models.CharField(max_length=30, unique=True, validators=[ping.models.validate_ip]),
        ),
    ]
